### ISSUE TITLE
May I ask when this project will be open-sourced?

### ISSUE THREAD

**Issue by Seperendity** [aluo-x/BrainDiVE#1]
That's fantastic, thank you again for your excellent work.

**Comment by aluo-x** [comment]
I've just pushed the core code. I will still need to cleanup the code so there is an easy to use demo. 

I will also release the encoder weights. 

See https://github.com/aluo-x/BrainDiVE/blob/main/run_brain_guidance_category.py#L266 for a basic usage example for your own fMRI encoder & brain region.
